#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-prefork
Version  : 1.04
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/A/AD/ADAMK/prefork-1.04.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/A/AD/ADAMK/prefork-1.04.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libp/libprefork-perl/libprefork-perl_1.04-2.debian.tar.xz
Summary  : 'Optimized module loading for forking or non-forking processes'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-2.0
Requires: perl-prefork-license = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Module::Install::DSL)

%description
NAME
prefork - Optimized module loading for forking or non-forking processes
SYNOPSIS
In a module that normally delays module loading with require

%package dev
Summary: dev components for the perl-prefork package.
Group: Development
Provides: perl-prefork-devel = %{version}-%{release}

%description dev
dev components for the perl-prefork package.


%package license
Summary: license components for the perl-prefork package.
Group: Default

%description license
license components for the perl-prefork package.


%prep
%setup -q -n prefork-1.04
cd ..
%setup -q -T -D -n prefork-1.04 -b 1
mkdir -p deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/prefork-1.04/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-prefork
cp LICENSE %{buildroot}/usr/share/package-licenses/perl-prefork/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.26.1/prefork.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/prefork.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-prefork/LICENSE
